### ISSUE TITLE
LeaderFollowerTeamTest test failure

### ISSUE THREAD

**Issue by sagenschneider** [sagenschneider/OfficeFloor#105]
[INFO] Running net.officefloor.frame.impl.spi.team.LeaderFollowerTeamTest
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.967 s <<< FAILURE! - in net.officefloor.frame.impl.spi.team.LeaderFollowerTeamTest
[ERROR] testHighLoad(net.officefloor.frame.impl.spi.team.LeaderFollowerTeamTest)  Time elapsed: 0.233 s  <<< FAILURE!
junit.framework.AssertionFailedError: Thread LeaderFollowerTeamSource-2 should be terminated expected:<TERMINATED> but was:<RUNNABLE>
	at net.officefloor.frame.impl.spi.team.LeaderFollowerTeamTest.leaderFollowerTest(LeaderFollowerTeamTest.java:112)
	at net.officefloor.frame.impl.spi.team.LeaderFollowerTeamTest.testHighLoad(LeaderFollowerTeamTest.java:67)

**Comment by sagenschneider** [comment]
Duplicate of #84
