### ISSUE TITLE
Make windows compatible

### ISSUE THREAD

**Issue by sagenschneider** [sagenschneider/OfficeFloor#312]
Current development has been Linux focused.   This is because target deployments are Linux cloud environments.

However, need to support Windows environments (particularly for development).  Therefore, need to get build running on Windows to ensure compatible with Windows.

Item identifying Windows issue:

```
net.officefloor.demo.RegisterRequestServiceTest  Time elapsed: 0 sec  <<< ERROR!
Failed to source OfficeType definition from OfficeSource net.officefloor.compile.impl.ApplicationOfficeFloorSource$ApplicationOfficeSource
java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:492)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
        at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
        at java.nio.file.Files.createTempDirectory(Files.java:991)
        at net.officefloor.web.resource.build.TemporaryDirectoryFileCacheService$TemporaryDirectoryFileCache.<init>(TemporaryDirectoryFileCacheService.java:89)
        at net.officefloor.web.resource.build.TemporaryDirectoryFileCacheService.createFileCache(TemporaryDirectoryFileCacheService.java:67)
        at net.officefloor.web.resource.impl.HttpResourceStoreImpl.<init>(HttpResourceStoreImpl.java:157)
        at net.officefloor.web.resource.build.HttpResourceArchitectEmployer.informWebArchitect(HttpResourceArchitectEmployer.java:253)
        at net.officefloor.woof.WoofLoaderExtensionService.extendOffice(WoofLoaderExtensionService.java:571)
        at net.officefloor.compile.impl.structure.OfficeNodeImpl.sourceOffice(OfficeNodeImpl.java:555)
        at net.officefloor.compile.impl.structure.OfficeNodeImpl.sourceOfficeTree(OfficeNodeImpl.java:623)
        at net.officefloor.compile.impl.structure.OfficeFloorNodeImpl.lambda$sourceOfficeFloorTree$42(OfficeFloorNodeImpl.java:750)
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:356)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
        at net.officefloor.compile.impl.util.CompileUtil.source(CompileUtil.java:330)
        at net.officefloor.compile.impl.structure.OfficeFloorNodeImpl.sourceOfficeFloorTree(OfficeFloorNodeImpl.java:749)
        at net.officefloor.compile.impl.OfficeFloorCompilerImpl.compile(OfficeFloorCompilerImpl.java:635)
        at net.officefloor.test.OfficeFloorRule$1.evaluate(OfficeFloorRule.java:155)
        at net.officefloor.spring.test.SpringRule$1.lambda$evaluate$1(SpringRule.java:92)
        at net.officefloor.spring.SpringSupplierSource.captureApplicationContext(SpringSupplierSource.java:124)
        at net.officefloor.spring.test.SpringRule$1.evaluate(SpringRule.java:88)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

```

**Comment by sagenschneider** [comment]
Resolved by #315
