### ISSUE TITLE
SocketManagerStressTest - Address already in use - test failure

### ISSUE THREAD

**Issue by sagenschneider** [sagenschneider/OfficeFloor#83]
[INFO] Running net.officefloor.server.SocketManagerStressTest
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.255 s <<< FAILURE! - in net.officefloor.server.SocketManagerStressTest
[ERROR] testMultiClientThreaded(net.officefloor.server.SocketManagerStressTest)  Time elapsed: 10.02 s  <<< ERROR!
java.net.BindException: Address already in use
	at net.officefloor.server.SocketManagerStressTest.startServer(SocketManagerStressTest.java:129)
	at net.officefloor.server.SocketManagerStressTest.testMultiClientThreaded(SocketManagerStressTest.java:104)

**Comment by sagenschneider** [comment]
[INFO] Running net.officefloor.server.ssl.SslThreadLocalPoolSocketManagerTest
[ERROR] Tests run: 24, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 12.204 s <<< FAILURE! - in net.officefloor.server.ssl.SslThreadLocalPoolSocketManagerTest
[ERROR] testSendHeaderOnly(net.officefloor.server.ssl.SslThreadLocalPoolSocketManagerTest)  Time elapsed: 10.031 s  <<< ERROR!
java.net.BindException: Address already in use

**Comment by sagenschneider** [comment]
Resolved #159
